# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev
    - libgsl0-dev
    - libcairo2-dev
  homebrew:
    packages:
    - cairo
    - gsl


matrix:
  include:
   - env: ARGS="--flag inline-c:gsl-example"
   - env: ARGS="--stack-yaml stack-lts-12.14.yaml --flag inline-c:gsl-example"
   # gtk2hs-buildtools is not present in nightly a bit of a pain to install,
   # skip it for now
   - env: ARGS="--stack-yaml stack-nightly-2018-10-24.yaml"
   - env: ARGS="--flag inline-c:gsl-example"
     os: osx

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://get.haskellstack.org/stable/osx-x86_64.tar.gz | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

# This line does all of the work: installs GHC if necessary, build the library,
# executables, and test suites, and runs the test suites. --no-terminal works
# around some quirks in Travis's terminal implementation.
script: stack --no-terminal --install-ghc test --haddock $ARGS

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - .stack-work
  - inline-c/.stack-work/
  - inline-c-cpp/.stack-work/
  - sample-cabal-project/.stack-work/
